from easygui import *
import sys
import Tkinter
import tkMessageBox
msgbox("Welcome to online payment service")
while 1:
 a = choicebox("Recharge your ...",choices=["Mobile","D2H Box","Telephone"])
 if a == "Mobile":
    a0 = ccbox("You have opted for Mobile Recharge")
    a1 = enterbox("Please enter your name")
    a3 = enterbox("City")
    a4 = enterbox("District")
    a5 = enterbox("State")
    a6 = choicebox("Please chosse your carrier",choices= ["Idea","Jio","Vodafone","Airtel"])
    a7 = choicebox("please choose payment option",choices= ["Debit card","Credit card","Paytm"])
    a8 = choicebox("Please choose your bank",choices= ["ICICI","Axis Bank","SBI"])
    a9 = enterbox("Enter Card number")
    a10 = enterbox("Enter Card holder's name")
    a11 = enterbox("Enter cvv")
    a12 = enterbox("Enter amount of recharge")
    a2 =  enterbox("Enter the otp sent by bank on your registered number.Never share this with anyone")
    a13 = ccbox("Congratulations Recharge done sucessfully!!")
    sys.exit(0)
 elif a == "D2H Box":
      b0 = ccbox("You have opted for D2H Recharge")
      b1 = enterbox("Please enter your name")
      b3 = enterbox("City")
      b4 = enterbox("District")
      b5 = enterbox("State")
      b6 = choicebox("Please chosse your service provider",choices= ["Videocon","Tata Sky","DEN"])
      b7 = choicebox("please choose payment option",choices= ["Debit card","Credit card","Paytm"])
      b8 = choicebox("Please choose your bank",choices= ["ICICI","Axis Bank","SBI"])
      b9 = enterbox("Enter Card number")
      b10 = enterbox("Enter Card holder's name")
      b11 = enterbox("Enter cvv")
      b12 = enterbox("Enter amount of recharge")
      b2 =  enterbox("Enter the otp sent by bank on your registered number.Never share this with anyone")
      b13 = ccbox("Congratulations Recharge done sucessfully!!")
      sys.exit(0)
if a == "Telephone":
   c0 = ccbox("You have opted for Telephone Recharge")
   c1 = enterbox("Please enter your name")
   c3 = enterbox("City")
   c4 = enterbox("District")
   c5 = enterbox("State")
   c6 = choicebox("Please chosse your carrier",choices= ["BSNL","Tata Docomo"])
   c7 = choicebox("please choose payment option",choices= ["Debit card","Credit card","Paytm"])
   c8 = choicebox("Please choose your bank",choices= ["ICICI","Axis Bank","SBI"])
   c9 = enterbox("Enter Card number")
   c10 = enterbox("Enter Card holder's name")
   c11 = enterbox("Enter cvv")
   c12 = enterbox("Enter amount of recharge")
   c2 =  enterbox("Enter the otp sent by bank on your registered number.Never share this with anyone")
   c13 = ccbox("Congratulations Recharge done sucessfully!!")
   sys.exit(0)      
else:
     sys.exit(0)
